title: StayCool21
description: CS major @ SIUE
baseurl: ""
url: https://staycool21.github.io

theme: cvless

# site settings
taglong: CS major @ SIUE
tagshort: Jekyll theme

# author settings
author: StayCool21
name: Luke Welsh
email: lwelsh@siue.edu
photo: assets/files/profilephoto.png
address: STL
# phone: +1 234 567 890

# social media links
social:
  github: StayCool21

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
